### ISSUE TITLE
Use case: Single dataset per project (repo on Github, view and annex on OSF)

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#10]
OSF supports one add-on per project. An addon can be GitHub/lab/Bitbucket and identify a single repo. We could publish a DataLad dataset on GitHub and put its annex on OSF. This way, we would have OSF render the view of the dataset, and hosts its annex, but have full featured (and importantly full-speed) Git-related functionality on GitHub.

**Comment by adswa** [comment]
Closing this, its possible now!
