### ISSUE TITLE
Q: is "import OSF project" functionality also implemented?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-osf#108]
I know that "import" part of git annex protocol is not yet implemented: https://git-annex.branchable.com/design/external_special_remote_protocol/export_and_import_appendix/ but I wondered if may be some crawling with addurls was done like in https://github.com/templateflow/datalad-osf by @oesteban ?  if it is not ATM, then probably worth adding a note to http://docs.datalad.org/projects/osf/en/latest/intro.html#what-can-i-not-use-this-extension-for and point to the one from templateflow.

**Comment by mih** [comment]
With #106 one can publish git and annex parts of a dataset to OSF and clone it in full back from OSF. I do not plan to add individual URLs to each file version.

**Comment by yarikoptic** [comment]
the question is about importing/crawling existing (before datalad-osf upload) projects on OSF.  That is what `git annex import` does for e.g. `directory` special remote.

**Comment by sappelhoff** [comment]
related to #97

**Comment by yarikoptic** [comment]
yes, it does! pretty much answering the original question, thus closing, thank you !
