### ISSUE TITLE
"git-annex: That remote does not support exports."

### ISSUE THREAD

**Issue by sappelhoff** [datalad/datalad-osf#109]
following http://docs.datalad.org/projects/osf/en/latest/exporthumandata.html

I did `git annex export HEAD --to osf` which worked fine, but somehow one file errored during the upload:

> (recording state in git...)
git-annex: export: 1 failed

how can I upload that file once more? EDIT: I don't even know which file errored out ... is there some log that I could check?

Calling `git annex export HEAD --to osf` again now yields

> git-annex: That remote does not support exports.

---

for now I solved the issue by manually uploading the single missing file (I was lucky and found which one was giving an error)

**Comment by mih** [comment]
Can you please report what version of datalad-osf you were using, and whether it was the same for both attempts?

**Comment by sappelhoff** [comment]
Thanks, your question was what brought me on the right track. In the mid of my up and downloading I installed https://github.com/templateflow/datalad-osf ... and thus the datalad/datalad-osf wasn't even pip installed at that point in time (or there was a hidden name error of some point).
