### ISSUE TITLE
Enable PR builds on Readthedocs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-osf#115]
This would make (p)reviewing PRs like #114 much easier. A maintainer needs to enable this on readthedocs.org -> Admin -> Advanced settings -> [x] Build pull requests for this project

**Comment by mih** [comment]
@adswa you are maintainer now.

**Comment by mih** [comment]
The setting was on already, no idea why it didn't build.

**Comment by adswa** [comment]
Thx! It looks like it lacks access to the Read the Docs OAuth App for datalad. I've send a request that should land in the organization's owners inbox (@yarikoptic, @mih?). Feel free to decline the request if its scope is too broad.

**Comment by mih** [comment]
I granted it. I think we do want that feature for any RTD docs.

**Comment by adswa** [comment]
Cool, I'll resync the webhooks and will push an empty commit to see if I can trigger it

**Comment by adswa** [comment]
done!
