### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#117]
When #114 we should make a release.

I prepared a changelog: https://github.com/datalad/datalad-osf/commit/0391f5f084c66bae586e4400ead346322b6947ff

**Comment by adswa** [comment]
maybe also #111?

**Comment by mih** [comment]
> maybe also #111?

That would be nice. I don't have the juice for it now, though. There will be another release after that. It would also be good to have feedback on https://github.com/datalad/datalad/issues/4676 before.

**Comment by adswa** [comment]
> There will be another release after that

True. And I just realized that I did a classic handbook fauxpax and merged in #114 (i.e., the ``latest`` docs currently document yet unreleased functionality), so an earlier release may be better.

**Comment by mih** [comment]
Done
