### ISSUE TITLE
datalad: Unknown command 'osf-credentials'

### ISSUE THREAD

**Issue by joeyzhou98** [datalad/datalad-osf#119]
**Describe the bug**
Following the documentation to the letter on http://docs.datalad.org/projects/osf/en/latest/settingup.html, when I try to call `datalad osf-credentials`, it seems like `osf-credentials` is an unknown command

**To Reproduce**
1) `pip install datalad-osf`
2)  `datalad osf-credentials`

![image](https://user-images.githubusercontent.com/35869923/87714871-70c33400-c77a-11ea-92ee-de0271cc90a3.png)

If applicable, attach screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]

**Comment by sappelhoff** [comment]
For that to work you need to do `pip install --upgrade https://api.github.com/repos/datalad/datalad-osf/zipball/master`.

The docs you were reading are the *latest* docs, referring to the development version.

In the stable version that you can obtain via pypi, `datalad osf-credentials` is not yet available (but see #117 ).

**Comment by mih** [comment]
I will make a release today, and then it will work.
