### ISSUE TITLE
Unable to provide OSF credentials

### ISSUE THREAD

**Issue by chrispycheng** [datalad/datalad-osf#124]
**Bug description**
`(dl-osf) user@server: ~/path$ datalad osf-credentials
[ERROR  ] Failed to create the collection: Prompt dismissed.. [SecretService.py:get_preferred_collection:59] (InitError) `

**To Reproduce**
Type `datalad osf-credentials`

**Desktop:**
Don't think this part is relevant to the issue. Command was executed in a virtual environment on a server

**Expected behavior**
Expected this as output instead:
`You need to authenticate with 'https://osf.io' credentials. https://osf.io/settings/tokens provides information on how to gain access
token: <your token here>
You need to authenticate with 'https://osf.io' credentials. https://osf.io/settings/tokens provides information on how to gain access
token (repeat): <your token here>
osf_credentials(ok): [authenticated as <user> <e-mail>]`

**Additional context**
FYI keyring version is 21.3.0

**Comment by chrispycheng** [comment]
@yarikoptic

**Comment by yarikoptic** [comment]
Since you said server - is it on smaug or you're trying to do on your Mac laptop?

For quick workaround try https://github.com/datalad/datalad/wiki/FAQ#how-to-configure-insecure-local-credentials-store

**Comment by adswa** [comment]
Was this resolved?

**Comment by adswa** [comment]
I'll close this as I am assuming it is resolved, please reopen if I am wrong
