### ISSUE TITLE
unable to clone: "fatal: unable to find remote helper for 'osf'"

### ISSUE THREAD

**Issue by chrhaeusler** [datalad/datalad-osf#133]
Hey,

I've set up datalad-osf (debian buster; datalad v0.13.4; datalad-osf v0.20) on one system, and creating a sibling, pushing and cloning works fine.
Nevertheless on another system (debian buster; datalad v0.13.4; datalad-osf v0.20), I get the following message trying to clone a dataset:

```
chris@psyinfolaf:/home/chris$ datalad clone osf://xxxxx/ studyforrest-speechannotation
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                                                                                                                                                                                            
| - osf://xxxxx/
  CommandError: 'git clone --progress osf://xxxxx/ /home/chris/studyforrest-speechannotation' failed with exitcode 128 [err: 'Cloning into '/home/chris/studyforrest-speechannotation'...
fatal: unable to find remote helper for 'osf''] [install(/home/chris/studyforrest-speechannotation)] 
install(error): /home/chris/studyforrest-speechannotation (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- osf://xxxxx/
  CommandError: 'git clone --progress osf://xxxxx/ /home/chris/studyforrest-speechannotation' failed with exitcode 128 [err: 'Cloning into '/home/chris/studyforrest-speechannotation'...
fatal: unable to find remote helper for 'osf'']]
```

Any ideas what might be the problem?

Kind regards
Chris

**Comment by adswa** [comment]
That sounds like ``datalad-osf`` isn't properly installed on your other system - how did you install it?

**Comment by chrhaeusler** [comment]
I used
```
 python3 -m pip install datalad-osf
```

**Comment by adswa** [comment]
oh... I'm glad it works, but normally you shouldn't need to use ``sudo``, though.
Also, it may be a good idea to create a virtualenv (``virtualenv --python=python3 ~/venv/osf``), activate this venv, and install software directly via ``pip install ...`` instead of going the detour with ``python3 -m``.

**Comment by adswa** [comment]
Anyway - Closing, happy that it works :)
