### ISSUE TITLE
Remove osfclient subtree upon 0.0.5 osfclient release

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-osf#137]
Leaving this here as a mental note/reminder:
One the osfclient is released in version 0.0.5 we can

- remove the osfclient subtree
- add ``osfclient >= 0.0.5`` to the requirements
- release ``0.3``
- continue with https://github.com/datalad/datalad-extensions/pull/24

**Comment by mih** [comment]
This is done, and with 0.2.3(.1) also reflected in the PyPi release.
