### ISSUE TITLE
git-remote helper ignores path in URL

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-osf#139]
Originally reported here: https://github.com/datalad/datalad/issues/5387

Culprit:
Datalad tries to clone a subdataset by appending the path to the URL of the subdataset. This would be fine if it simply fails and `clone` proceeds with the next candidate URL. However, it isn't properly failing. Instead git-remote helper only uses `urlparse(url).netloc` to instantiate the project object, ignoring there's `urlparse(url).path`, too, which if it was appended would lead to correct failure. This leads to `osf://ID/whatever` being treated as `osf://ID/`. In case of such a subdataset (as shown in the original issue) we clone the superdataset instead.

As far as I can tell, there's no case in which a URL like `https://osf.io/jr5vx/some/path` would ever lead to a project. So, I'm going to push a fix where git-remote will fail early on such a URL.
If it turns out, that such a URL could indeed be valid, then we would need to pass `netloc + path` to osf client and let it fail whenever it wants to.

**Comment by mih** [comment]
Here is the issue I was looking for in #140.

We do not want to support any paths: https://github.com/datalad/datalad-osf/issues/30
