### ISSUE TITLE
git-annex: unable to use special remote due to protocol error

### ISSUE THREAD

**Issue by oesteban** [datalad/datalad-osf#146]
**Describe the bug**
A command line that used to work now crashes with:

```
$ datalad create-sibling-osf --title "NiPreps testing - ${DATASET_NAME}" -s osf --public --category data -d ./${DATASET_NAME}
CommandError: 'git annex initremote osf-storage encryption=none type=external externaltype=osf autoenable=true node=7mvnz -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /Users/oesteban/sdcflows-tests/ds000210
initremote osf-storage

failed
Traceback (most recent call last):
  File "/Users/oesteban/.anaconda/bin/git-annex-remote-osf", line 8, in <module>
    sys.exit(main())
  File "/Users/oesteban/.anaconda/lib/python3.8/site-packages/datalad_osf/annex_remote.py", line 305, in main
    remote = OSFSpecialRemote(master)
  File "/Users/oesteban/.anaconda/lib/python3.8/site-packages/datalad_osf/annex_remote.py", line 83, in __init__
    self.configs['node'] = 'The OSF URL for the remote'
AttributeError: 'OSFSpecialRemote' object has no attribute 'configs'
  external special remote protocol error, unexpectedly received "<EOF>" (unable to parse command)
git-annex: unable to use special remote due to protocol error
git-annex: initremote: 1 failed
```

Although I had just updated to datalad-osf==0.2.2 (and osfclient==0.0.5), rolling back to my previous settings (0.2.0 + 0.0.3) resulted on the same error.

**To Reproduce**

I suspect that datalad-osf didn't quite like I used ``--initial-branch=main`` for the datalad crate command (see https://github.com/datalad/datalad/issues/4997#issuecomment-712933899):
```
datalad create -c text2git -D "Test Dataset for NiPreps derived from OpenNeuro's ${DATASET_NAME}" ${DATASET_NAME} --initial-branch=main
```

**Comment by oesteban** [comment]
The problem also occurs without `--initial-branch=main`

**Comment by bpoldrack** [comment]
> AttributeError: 'OSFSpecialRemote' object has no attribute 'configs'

That's strange. Didn't look into it yet, but FTR: `configs` is supposed to be inherited from `annexremote`'s `SpecialRemote` class.

**Comment by oesteban** [comment]
Yes, but I can't be the definition anywhere (looking at https://github.com/datalad/AnnexRemote/blame/master/annexremote/annexremote.py#L45).

I see `.info` FWIW

**Comment by bpoldrack** [comment]
Now I'm confused. This is what I see browsing directly in that repo. So this should be master:

https://github.com/Lykos153/AnnexRemote/blob/2c1577884531404462fac21a47cd064b04f4fc49/annexremote/annexremote.py#L104

And we do use this elsewhere.

**Comment by bpoldrack** [comment]
Ah, now I see it. You reference a fork in datalad organization that isn't up-to-date.

**Comment by oesteban** [comment]
I think that's where datalad-osf is importing from

**Comment by oesteban** [comment]
@bpoldrack pinning annexremote to their current master worked out

```
pip install git+https://github.com/Lykos153/AnnexRemote.git
```

Now it seems it's importing the right version.

My environment was originally set up with conda/conda-forge, if that adds some relevant detail.

**Comment by bpoldrack** [comment]
> I think that's where datalad-osf is importing from

Not really. setup.cfg just specifies the package name. Should come from pypi.

> My environment was originally set up with conda/conda-forge, if that adds some relevant detail.

Might be. Need to look into it.

> and consequently datalad create-sibling-osf worked like a charm.

Ok, cool. Will remove the bug label, but keep this open to investigate how one can end up with that fork installed.

**Comment by mih** [comment]
OK, despite not knowing what is really happening, I have deleted the `datalad/AnnexRemote` fork. So this should be good now.

I am closing the issue, but feel free to reopen, if this pops up again, and we cannot avoid a more thorough investigation.

**Comment by oesteban** [comment]
Thanks for the help. I think it was just a messed-up environment.
