### ISSUE TITLE
Adjust description with the actual ID

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-osf#149]
Currently description is provided to `create_node` so by that time it doesn't know the id so wording contains generic "datalad cloned from a 'osf://ID' URL...".  But ID should be known after that operation and I bet there is an API end point to change the description, so ideally to improve user-experience description should be adjusted after that new node created with the actual ID of the node.

**Comment by adswa** [comment]
ummmhhh I'm not sure I understand what you mean because I think you suggested that already and I implemented it and it is merged and working?

**Comment by adswa** [comment]
https://github.com/datalad/datalad-osf/pull/126

**Comment by yarikoptic** [comment]
I must have been blind white reading the code. Sorry for the noise!!
