### ISSUE TITLE
Delete files from osf-storage

### ISSUE THREAD

**Issue by hvgazula** [datalad/datalad-osf#186]
Hello, I was wondering if there is a way to delete files from osf-storage. For example, I added a file and pushed it to osf-annex-storage. Now, I used `datalad remove {filename} --reckless kill` which removed the file and its references from the local repository. However `datalad push --to osf-annex-strorage` does not remove the file/reference from osf. Please advise.

**Comment by adswa** [comment]
Hey, there is no datalad command to drop from siblings, but ``git annex drop`` has a ``--from`` option which allows to specify a sibling: https://git-annex.branchable.com/git-annex-drop/. Hope this helps. :) I'll close this issue as answered, but feel free to reopen if you disagree.

**Comment by hvgazula** [comment]
Thanks for the response. Is it worth having this option in datalad as well?

**Comment by adswa** [comment]
There is a recent issue asking for it: https://github.com/datalad/datalad/issues/7515. We placed it as "wishlist" item to the issue tracker. Feel free to thumbs-up the issue in support or comment. :)
