### ISSUE TITLE
Can `datalad osf-credentials` be used non-interactively?

### ISSUE THREAD

**Issue by asmacdo** [datalad/datalad-osf#191]
I am trying to use datalad osf in a github action. I have a github secret containing an osf token, but AFAICT it isn't possible to authenticate with OSF programatically.

what I wanted to be able to do:

`datalad osf-credentials --token {{ secrets.osf_token }}`

**Comment by adswa** [comment]
Hey, you should be able to do this via an environment variable: ``OSF_TOKEN``. Then the ``osf-credentials`` commands isn't needed at all.
