### ISSUE TITLE
Ability to perform testing against OSF

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#20]
Maybe have a dedicated user, and a prepared access token (#17). It would need the ability to clean up projects on OSF to avoid leaving behind a huge mess.

**Comment by adswa** [comment]
I have set up a test account with a token. Shall I add it to the .travis.yml file?

**Comment by mih** [comment]
I am not certain how this is done best. I think "secrets" can be configured on github to avoid publishing the credential. Anybody could do harm with it, otherwise.

**Comment by adswa** [comment]
Yes, but I have insufficient permissions in this repo to create secrets. I'll send it via a different channel.

**Comment by mih** [comment]
You should have access now.

**Comment by adswa** [comment]
thx. I have added the following secrets:
`OSF_TOKEN`, `OSF_USERNAME`, `OSF_PASSWORD`

**Comment by adswa** [comment]
(those can be used in GitHub workflows, so tests that use those need to be in a workflow)

**Comment by adswa** [comment]
@mjboos takes a look at this now :+1:

**Comment by mjboos** [comment]
With #54 we can use the secrets as environment variables in travis CI and test against OSF.

**Comment by bpoldrack** [comment]
FTR: I have a routine to create a project on OSF in PR #29 and I'm about to one for deleting a project. Will cherry-pick both and file a separate PR, since this should be useful for test helpers independently on the setup helper PR.

Ping @mih , @kousu  FYI

**Comment by mih** [comment]
Done now #57
