### ISSUE TITLE
Need for rate-limiting?

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#28]
Work on #25 I seem to have been blocked by OSF, possibly because of my excessive API use.

**Comment by adswa** [comment]
https://github.com/osfclient/osfclient/pull/105?

**Comment by mjboos** [comment]
OSF client has a rate limit of 1/sec, but the OSF API allows only 100 unauthenticated requests per hour (or 10k per day for authenticated).
I'm not sure if it make sense to catch the error code and automatically retry, but we should at least output the error with the information how long the user has to wait.

**Comment by mih** [comment]
Thanks @mjboos for digging out those numbers. That would mean that uploading large numbers of files can take a very long time. This should be features prominently in this docs!

**Comment by TheDragon246** [comment]
@mih It is mentioned here-
https://developer.osf.io/#tag/Errors-and-Error-Codes

> `429` Too Many Requests
> 
> The user has sent too many requests in a given amount of time.
> 
> Wait at least the amount of time specified in the Retry-After header of the response before sending another request.
> 
> Authenticated requests have a rate limit of 10,000/day.
> 
> Unauthenticated requests have a rate limit of 100/hour.

**Comment by yarikoptic** [comment]
I have not looked into OSF API but just spotted that github api informs in the response headers about how many requests are left and when next time would be reset:
```shell
$> curl --silent -i https://api.github.com/users/octocat | grep -i Rate
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 51
X-Ratelimit-Reset: 1594912768

$> curl --silent -i https://api.github.com/users/octocat | grep -i Rate
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 50
X-Ratelimit-Reset: 1594912768
```
That allows a client to be "smart" about it instead of just guessing or introducing some sleeping.
If OSF doesn't provide such information ATM, would be worth suggesting it.

**Comment by yarikoptic** [comment]
actually silly me: https://github.com/datalad/datalad-osf/issues/28#issuecomment-646098676 also provides needed information `Retry-After` header should also be sufficient - just sleep for that amount if found in the response header

**Comment by adswa** [comment]
The next release of osfclient will include a rate limiter, and IIRC, #136 has brought it into the code base already - so we now have one.
