### ISSUE TITLE
Make projects 1:1 with remotes

### ISSUE THREAD

**Issue by kousu** [datalad/datalad-osf#30]
OSF provides lots of features for data-organization. You can have "linked" and "component" projects, each with their own IDs and URLs. For example, I made https://osf.io/fg8jy/ which has a child component https://osf.io/tkrbw/, which I've marked with the "data" icon, and used `git-annex-remote-osf` to upload a copy of its own source code:

![Screenshot_2020-06-17_07-22-26](https://user-images.githubusercontent.com/987487/84892937-71c65000-b06c-11ea-8380-e4c5ddea2294.png)

Here's the commands I used:

```
mkdir t1
cd t1
cp -r ../* .; rm -rf .git
git init
git annex init
git annex add .
git commit -m "Import datalad_osf"
export OSF_USERNAME="nguenthe@uwaterloo.ca"
export OSF_PASSWORD="$(pass academic/osf.io | head -n1)"
git annex initremote osf type=external externaltype=osf encryption=none project='https://osf.io/tkrbw/'
git annex -d copy . --to=osf 
```

![Screenshot_2020-06-17_07-23-29](https://user-images.githubusercontent.com/987487/84893814-d930cf80-b06d-11ea-8447-4252e1e29361.png)

I feel the [`objpath` parameter](https://github.com/datalad/datalad-osf/blob/cb2f16167dba1db36b6721e06a21d4fae9e9abb6/datalad_osf/remote.py#L107) duplicates the functionality of OSF subcomponents, while [complicating](https://github.com/datalad/datalad-osf/blob/cb2f16167dba1db36b6721e06a21d4fae9e9abb6/datalad_osf/remote.py#L129) [things](https://github.com/datalad/datalad-osf/blob/cb2f16167dba1db36b6721e06a21d4fae9e9abb6/datalad_osf/remote.py#L135) needlessly, most of all in explaining it to the user in the UI. The very first thing I as a user am going to ask here is: why is there a "git-annex" folder inside of the "annex" folder?

The more options software has, the more flexible it is, the more opaque and difficult to use it is.

**Comment by kousu** [comment]
Relatedly,

https://github.com/datalad/datalad-osf/blob/cb2f16167dba1db36b6721e06a21d4fae9e9abb6/datalad_osf/remote.py#L101-L103

as far as I can tell there is only ever one storage per project ( / component project). When you make a new component it insists you pick a single location to associate with it, and there's no UI anywhere for adding more, despite what the API might seem to imply.

![Screenshot_2020-06-17_07-27-27](https://user-images.githubusercontent.com/987487/84893588-793a2900-b06d-11ea-9942-572a0791b0db.png)

**Comment by mih** [comment]
If you enable an "add-on" like Github or DropBox, they will show up as additonal storages.

**Comment by kousu** [comment]
In that case maybe people can just use the `git-annex-remote-dropbox` or `git-annex-remote-git`?

**Comment by mih** [comment]
There is always a different way, of course. But this is something that OSF readily supports for years, and is a very useful feature to link different services in a single place. That is actually my favorite feature of OSF.

**Comment by mih** [comment]
I am thinking about this more after having started working on the export functionality. There are two principle direction AFAICS:

- be able to put an export and an annex into the same project
- or not

If we want to have both (which can make sense for storing content that a dataset maintains in multiple branches, but also provide a browse-able view) we need to have a way to specific where these pieces live within the storage unit.

Alternatively, we say (all of the below):

- an annex is a dedicated project
- each branch export is a dedicated project
- any manual tailoring should happen in a dedicated projects that may make use of any of the projects above.

I will keep thinking about downsides, but at first glance this sounds like a sensible approach to me, and seems to be in line with the OP.

**Comment by kousu** [comment]
I like that. Compare github: https://github.com/datalad/datalad-osf/tree/master/ is one view, https://github.com/datalad/datalad-osf/tree/flatremotes is another. But https://github.com/datalad/datalad-osf/ contains them both. The URLs on OSF aren't readable or hierarchical like that but you could arrange something very close.

This would have to be up in datalad territory I guess?

**Comment by mih** [comment]
Cool, and yes! So let me look at #44

**Comment by bpoldrack** [comment]
Since requested via mattermost: I agree. :)

**Comment by mih** [comment]
Done with the merge of #44
