### ISSUE TITLE
Cut a release before 2pm UTC+2, presentation in wrap-up: TODOs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-osf#63]
Please add and mark TODOs as you see fit:

- [x] set up ``.zenodo.json`` with all contributors (@TheDragon246 is on it)
- [x] come up with a one-sentence description (suggestions welcome in this issue)
- [x] It would be cool to have the remaining files that https://github.com/datalad/datalad-osf/community suggests: ``CONTRIBUTING.md``, ``CODE_OF_CONDUCT.md``
- [ ] It would be cool to have Issue and Pull request templates (can also be added in https://github.com/datalad/datalad-osf/community)
- [x] Slides added to project pitch: https://docs.google.com/presentation/d/1gdYpBeLaJ3cn9OoQyZhecvPZiTRqJ_wghdAgMUMgQhg/edit#slide=id.g89d8c40fe0_0_0. What would be cool: add a gif that depicts the workflow 
- [x] PyPi release

**Comment by DorienHuijser** [comment]
Sentence: "In this project we developed a way for DataLad to interact with OSF, enabling version control of your OSF dataset!" (?) Not sure if this covers all functionality though

**Comment by DorienHuijser** [comment]
The readme contains some first start for contributing guidelines, but maybe we could also steal them from other projects? :)

**Comment by adswa** [comment]
> Sentence: "In this project we developed a way for DataLad to interact with OSF, enabling version control of your OSF dataset!" (?) Not sure if this covers all functionality though

here is an example from another extension: https://zenodo.org/record/3685962#.XusjRaaxUUE, maybe something similar?

**Comment by adswa** [comment]
There is a really comprehensive one in https://github.com/datalad/datalad/blob/master/CONTRIBUTING.md, maybe we can steal some of the applicable and useful elements, @DorienHuijser ?

**Comment by adswa** [comment]
#58 needs to be in contributing.md

**Comment by DorienHuijser** [comment]
I added issue templates but I cannot add a PR template 🤔

**Comment by DorienHuijser** [comment]
Code of conduct: see PR #72

**Comment by mih** [comment]
FTR: All functionality I dreamed about it now in `master`. This is pretty amazing!

**Comment by DorienHuijser** [comment]
Sentence: "This extension enables DataLad to work with the Open Science Framework (OSF). Use it to publish your dataset's data to an OSF project to utilize the OSF for dataset storage and sharing."

**Comment by DorienHuijser** [comment]
I will propose a first version of contributing guidelines soon

**Comment by TheDragon246** [comment]
https://github.com/stevemao/github-issue-templates
Any template from here could be used?

**Comment by DorienHuijser** [comment]
Hi @TheDragon246 there is already an issue template, just no pull request template!

**Comment by adswa** [comment]
There is a Zenodo record, and it has the description @DorienHuijser provided. Cite as:

Hanke, Michael, Poldrack, Benjamin, Wagner, Adina S., Huijser, Dorien, Sahoo, Ashish K., Boos, Moritz, … Guenther, Nick. (2020, June 18). datalad/datalad-osf. Zenodo. http://doi.org/10.5281/zenodo.3900278

:tada:
