### ISSUE TITLE
Make examples for different use cases

### ISSUE THREAD

**Issue by mjboos** [datalad/datalad-osf#69]
I think it's helpful to make different examples for different use cases.
These could be:

1. Just exporting (and later cloning) a dataset to OSF with human readable file structure.

2. Storing some files on Github and others on OSF.

3. Just using OSF as a remote for git annex.

2 and 3 could also be merged.

Any thoughts on other examples that would be helpful?

**Comment by adswa** [comment]
I think this captures the current functions well already :+1: 

It actually would be cool to have a public project on the OSF that others could try cloning (1). We could do this using our test account, right?

Shall we discuss #70 in here as well? The two issues are related.

**Comment by mjboos** [comment]
Good idea, that could be a fourth example (or merged with another one) - just cloning a public OSF repo with datalad.

**Comment by DorienHuijser** [comment]
Yes, was thinking this too: these examples assume a local dataset to be pushed to OSF, but I'm still missing the other way around: start using a dataset that is already on the OSF locally.

**Comment by DorienHuijser** [comment]
Proposal structure of the documentation:
- example.rst
  - Exporting a human-readable dataset to OSF 
  - Exporting a version-controlled dataset to OSF
  - Exporting version-controlled code to Github and data to OSF
  - Cloning a human-readable OSF dataset to your local PC
  - Cloning a version-controlled dataset to your local PC
- running.rst is actually empty at the moment, maybe we can remove it and create a separate .rst file for every use case?

**Comment by mjboos** [comment]
I'm not sure if we can decide ourselves if we clone a human readable or "cryptic" OSF dataset.

My personal preference is to have different example files, even if we have some redundancy in creating a simulated dataset, and describe different use cases in the introduction file.
I think it makes it easier for an user to find the code for his use case.

**Comment by DorienHuijser** [comment]
I agree, will create separate files for the 4 scenarios proposed above (the 4th being the 4th and 5th options combined)

**Comment by DorienHuijser** [comment]
Closing this because the separate files are now created
