### ISSUE TITLE
Investigate what happens to version history on file deletion

### ISSUE THREAD

**Issue by kousu** [datalad/datalad-osf#8]
^ 

if we create a file, delete it, and reupload it on OSF does the version numbering start over again? That would break permalinks hard.

**Comment by mjboos** [comment]
Yes it does - new id, new SHA, new version history, new url.

**Comment by mih** [comment]
I can confirm @mjboos's report

**Comment by adswa** [comment]
Closing this FYI issue, thanks for the reports!
