### ISSUE TITLE
--mode {annexstore,exporttree} -> --mode {annex,export}

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#88]
I do not see what the longer labels contribute in addition. Moreover, `annex` and `export` are the actual terms that can be found in the `git-annex` docs -- using different terms may make people wonder if there is something more to them -- which is not the case.

**Comment by adswa** [comment]
I agree - especially since I keep misspelling "exporttree" (so many t's...), and the notion of a tree likely isn't clear to everyone. ``annex`` and ``export`` are good choices IMO.

**Comment by mih** [comment]
Fixed with #91
